create table hr.countries (
    country_id   char(2 byte)
        constraint country_id_nn not null enable,
    country_name varchar2(60 byte),
    region_id    number
);

alter table hr.countries
    add constraint country_c_id_pk primary key ( country_id )
        using index enable;


-- sqlcl_snapshot {"hash":"252e47d62647de54956249a12cf79bfb710177ec","type":"TABLE","name":"COUNTRIES","schemaName":"HR","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>HR</SCHEMA><NAME>COUNTRIES</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>COUNTRY_ID</NAME><DATATYPE>CHAR</DATATYPE><LENGTH>2</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME><NOT_NULL><NAME>COUNTRY_ID_NN</NAME></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>COUNTRY_NAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>60</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>REGION_ID</NAME><DATATYPE>NUMBER</DATATYPE></COL_LIST_ITEM></COL_LIST><PRIMARY_KEY_CONSTRAINT_LIST><PRIMARY_KEY_CONSTRAINT_LIST_ITEM><NAME>COUNTRY_C_ID_PK</NAME><COL_LIST><COL_LIST_ITEM><NAME>COUNTRY_ID</NAME></COL_LIST_ITEM></COL_LIST><USING_INDEX></USING_INDEX></PRIMARY_KEY_CONSTRAINT_LIST_ITEM></PRIMARY_KEY_CONSTRAINT_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}