create table hr.databasechangelog_actions (
    id            varchar2(255 byte) not null enable,
    sequence      number not null enable,
    sql           clob,
    sxml          clob,
    author        varchar2(255 byte),
    filename      varchar2(255 byte),
    deployment_id varchar2(10 byte),
    status        varchar2(20 byte)
);

alter table hr.databasechangelog_actions
    add constraint databasechangelog_actions_pk
        primary key ( id,
                      author,
                      filename,
                      sequence )
            using index enable;


-- sqlcl_snapshot {"hash":"c13041b081fbac1d6cd7d50bf66b62a4f5d9bc95","type":"TABLE","name":"DATABASECHANGELOG_ACTIONS","schemaName":"HR","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>HR</SCHEMA><NAME>DATABASECHANGELOG_ACTIONS</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>ID</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>255</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME><NOT_NULL></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>SEQUENCE</NAME><DATATYPE>NUMBER</DATATYPE><NOT_NULL></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>SQL</NAME><DATATYPE>CLOB</DATATYPE><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>SXML</NAME><DATATYPE>CLOB</DATATYPE><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>AUTHOR</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>255</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>FILENAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>255</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>DEPLOYMENT_ID</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>10</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>STATUS</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>20</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM></COL_LIST><PRIMARY_KEY_CONSTRAINT_LIST><PRIMARY_KEY_CONSTRAINT_LIST_ITEM><NAME>DATABASECHANGELOG_ACTIONS_PK</NAME><COL_LIST><COL_LIST_ITEM><NAME>ID</NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>AUTHOR</NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>FILENAME</NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>SEQUENCE</NAME></COL_LIST_ITEM></COL_LIST><USING_INDEX></USING_INDEX></PRIMARY_KEY_CONSTRAINT_LIST_ITEM></PRIMARY_KEY_CONSTRAINT_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}