create table hr.databasechangeloglock (
    id          number(*, 0) not null enable,
    locked      boolean not null enable,
    lockgranted timestamp(6),
    lockedby    varchar2(255 byte)
);

alter table hr.databasechangeloglock
    add constraint pk_databasechangeloglock primary key ( id )
        using index enable;


-- sqlcl_snapshot {"hash":"123d189f5cb78866317dbdc4232220549e3557a6","type":"TABLE","name":"DATABASECHANGELOGLOCK","schemaName":"HR","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>HR</SCHEMA><NAME>DATABASECHANGELOGLOCK</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>ID</NAME><DATATYPE>NUMBER</DATATYPE><SCALE>0</SCALE><NOT_NULL></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>LOCKED</NAME><DATATYPE>BOOLEAN</DATATYPE><NOT_NULL></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>LOCKGRANTED</NAME><DATATYPE>TIMESTAMP</DATATYPE><SCALE>6</SCALE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>LOCKEDBY</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>255</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM></COL_LIST><PRIMARY_KEY_CONSTRAINT_LIST><PRIMARY_KEY_CONSTRAINT_LIST_ITEM><NAME>PK_DATABASECHANGELOGLOCK</NAME><COL_LIST><COL_LIST_ITEM><NAME>ID</NAME></COL_LIST_ITEM></COL_LIST><USING_INDEX></USING_INDEX></PRIMARY_KEY_CONSTRAINT_LIST_ITEM></PRIMARY_KEY_CONSTRAINT_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}