create table hr.employees (
    employee_id    number(6, 0),
    first_name     varchar2(20 byte),
    last_name      varchar2(25 byte)
        constraint emp_last_name_nn not null enable,
    email          varchar2(25 byte)
        constraint emp_email_nn not null enable,
    phone_number   varchar2(20 byte),
    hire_date      date
        constraint emp_hire_date_nn not null enable,
    job_id         varchar2(10 byte)
        constraint emp_job_nn not null enable,
    salary         number(8, 2),
    commission_pct number(2, 2),
    manager_id     number(6, 0),
    department_id  number(4, 0)
);

create unique index hr.emp_emp_id_pk on
    hr.employees (
        employee_id
    );

alter table hr.employees add constraint emp_salary_min check ( salary > 0 ) enable;

alter table hr.employees add constraint emp_email_uk unique ( email )
    using index enable;

alter table hr.employees
    add constraint emp_emp_id_pk
        primary key ( employee_id )
            using index hr.emp_emp_id_pk enable;


-- sqlcl_snapshot {"hash":"08fbae30a681f8513f8407de386bdfeb1783ea63","type":"TABLE","name":"EMPLOYEES","schemaName":"HR","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>HR</SCHEMA><NAME>EMPLOYEES</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>EMPLOYEE_ID</NAME><DATATYPE>NUMBER</DATATYPE><PRECISION>6</PRECISION><SCALE>0</SCALE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>FIRST_NAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>20</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>LAST_NAME</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>25</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME><NOT_NULL><NAME>EMP_LAST_NAME_NN</NAME></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>EMAIL</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>25</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME><NOT_NULL><NAME>EMP_EMAIL_NN</NAME></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>PHONE_NUMBER</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>20</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>HIRE_DATE</NAME><DATATYPE>DATE</DATATYPE><NOT_NULL><NAME>EMP_HIRE_DATE_NN</NAME></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>JOB_ID</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>10</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME><NOT_NULL><NAME>EMP_JOB_NN</NAME></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>SALARY</NAME><DATATYPE>NUMBER</DATATYPE><PRECISION>8</PRECISION><SCALE>2</SCALE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>COMMISSION_PCT</NAME><DATATYPE>NUMBER</DATATYPE><PRECISION>2</PRECISION><SCALE>2</SCALE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>MANAGER_ID</NAME><DATATYPE>NUMBER</DATATYPE><PRECISION>6</PRECISION><SCALE>0</SCALE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>DEPARTMENT_ID</NAME><DATATYPE>NUMBER</DATATYPE><PRECISION>4</PRECISION><SCALE>0</SCALE></COL_LIST_ITEM></COL_LIST><CHECK_CONSTRAINT_LIST><CHECK_CONSTRAINT_LIST_ITEM><NAME>EMP_SALARY_MIN</NAME><CONDITION>salary>0</CONDITION></CHECK_CONSTRAINT_LIST_ITEM></CHECK_CONSTRAINT_LIST><PRIMARY_KEY_CONSTRAINT_LIST><PRIMARY_KEY_CONSTRAINT_LIST_ITEM><NAME>EMP_EMP_ID_PK</NAME><COL_LIST><COL_LIST_ITEM><NAME>EMPLOYEE_ID</NAME></COL_LIST_ITEM></COL_LIST><USING_INDEX></USING_INDEX></PRIMARY_KEY_CONSTRAINT_LIST_ITEM></PRIMARY_KEY_CONSTRAINT_LIST><UNIQUE_KEY_CONSTRAINT_LIST><UNIQUE_KEY_CONSTRAINT_LIST_ITEM><NAME>EMP_EMAIL_UK</NAME><COL_LIST><COL_LIST_ITEM><NAME>EMAIL</NAME></COL_LIST_ITEM></COL_LIST><USING_INDEX></USING_INDEX></UNIQUE_KEY_CONSTRAINT_LIST_ITEM></UNIQUE_KEY_CONSTRAINT_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}