create table hr.locations (
    location_id    number(4, 0),
    street_address varchar2(40 byte),
    postal_code    varchar2(12 byte),
    city           varchar2(30 byte)
        constraint loc_city_nn not null enable,
    state_province varchar2(25 byte),
    country_id     char(2 byte)
);

create unique index hr.loc_id_pk on
    hr.locations (
        location_id
    );

alter table hr.locations
    add constraint loc_id_pk
        primary key ( location_id )
            using index hr.loc_id_pk enable;


-- sqlcl_snapshot {"hash":"aaca80f46c9de38024d6bc505b26b3e3f5752f58","type":"TABLE","name":"LOCATIONS","schemaName":"HR","sxml":"<TABLE  xmlns  =\"http://xmlns.oracle.com/ku\"  version  =\"1.0\"><SCHEMA>HR</SCHEMA><NAME>LOCATIONS</NAME><RELATIONAL_TABLE><COL_LIST><COL_LIST_ITEM><NAME>LOCATION_ID</NAME><DATATYPE>NUMBER</DATATYPE><PRECISION>4</PRECISION><SCALE>0</SCALE></COL_LIST_ITEM><COL_LIST_ITEM><NAME>STREET_ADDRESS</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>40</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>POSTAL_CODE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>12</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>CITY</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>30</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME><NOT_NULL><NAME>LOC_CITY_NN</NAME></NOT_NULL></COL_LIST_ITEM><COL_LIST_ITEM><NAME>STATE_PROVINCE</NAME><DATATYPE>VARCHAR2</DATATYPE><LENGTH>25</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM><COL_LIST_ITEM><NAME>COUNTRY_ID</NAME><DATATYPE>CHAR</DATATYPE><LENGTH>2</LENGTH><COLLATE_NAME>USING_NLS_COMP</COLLATE_NAME></COL_LIST_ITEM></COL_LIST><PRIMARY_KEY_CONSTRAINT_LIST><PRIMARY_KEY_CONSTRAINT_LIST_ITEM><NAME>LOC_ID_PK</NAME><COL_LIST><COL_LIST_ITEM><NAME>LOCATION_ID</NAME></COL_LIST_ITEM></COL_LIST><USING_INDEX></USING_INDEX></PRIMARY_KEY_CONSTRAINT_LIST_ITEM></PRIMARY_KEY_CONSTRAINT_LIST><DEFAULT_COLLATION>USING_NLS_COMP</DEFAULT_COLLATION><PHYSICAL_PROPERTIES><HEAP_TABLE></HEAP_TABLE></PHYSICAL_PROPERTIES></RELATIONAL_TABLE></TABLE>"}